arguably the criteria said the col should be flipped to all NA, but only because of preexisting issue. It's debatable what the right answer whould be here: Here's the summary of col with 'abc', 0 and 1 in it. Result of: cardinality 3 and naCnt 0 doesn't seem like the best thing?
colname: C20
coltype: None
nacnt: 0
stattype: Enum
cardinality: 3
hstart: 0.0
hstep: 1.0
hbrk: [u'0', u'1', u'abc']
hcnt: [1, 1, 100]
FAIL

AssertionError: trial 1: cardinality 3 should be 1